### ISSUE TITLE
api_response = api_instance.list_account() returns error "ValueError: Invalid value for `liability_type` (Mortgage), must be one of ['loan', 'debt', 'mortgage']"

### ISSUE THREAD

**Issue by zhuqf** [ms32035/firefly-iii-client#8]
can not find a way to turn off self.local_vars_configuration.client_side_validation without change the source code

**Comment by ms32035** [comment]
And you shouldn't. If the domain values are wrong, please submit a PR to the original apidocs repo. Otherwise, you can regenerate the package yourself, with a locally modified specification. See the following:
* https://github.com/ms32035/firefly-iii-client/blob/master/docker-compose.yml
* https://github.com/ms32035/firefly-iii-client/blob/master/Dockerfile
* https://github.com/ms32035/firefly-iii-client/blob/master/.generator/generate.sh#L9

The Pypi package follows API version, so I can't republish 1.4.0
